Styling for industry averages
growthtools/ad-spend-calc pull request #18
Opened 2020-10-09 19:28 UTC by kacyhulme

Fixes [this To Do]()

### Testing notes

1. 
1. 
1. 

### Other information

2020-10-12 11:38 UTC, kacyhulme commented
@codegoalie I got this working. It could use some refactoring. Open to your feedback.

2020-10-12 12:03 UTC, codegoalie requested changes
This looks good.

My one comment is about the overall organization of the code. Probably not something that needs to be addressed now, but something to consider in the future.

The only issue I saw is that the alternating row background is not working.

![image](https://user-images.githubusercontent.com/75132/95744504-66bdae00-0c61-11eb-9e55-ce0b9d04cc37.png)

2020-10-12 12:03 UTC, codegoalie commented on src/Averages.js
> +  const highAvgs = [
One thing to keep in mind is the single responsibility principle. In short, each aspect of the software should be responsible for one thing. A code smell to indicate that you might be working against that principle is a boolean parameter that only exists to toggle between 2 outcomes of the component. The `type` prop (although it's a string) is like that here. This component is responsible for assembling the `div`s of both the high and low averages: 2 responsibilities.

One potential solution would be do define 2 components `HighAverages` and `LowAverages`. These each would be very similar to this component without the switching logic.

A more DRY solution could also be to move the row content constants out of this component and into the `IndustryAverages` component. Then this component does only one thing: takes any JS object and returns a list of `div`s with the `key` and `value`of each attribute in the object.

There are probably other solutions too. Both of the two I've listed have their pros and cons.

2020-10-12 13:12 UTC, kacyhulme commented on src/Averages.js
> +  const highAvgs = [
@codegoalie I tried the first approach, breaking out the Low and High processes into two different components. [New branch. ](https://github.com/growthtools/ad-spend-calc/pull/20)

2020-10-13 11:31 UTC, codegoalie reviewed
@kacyhulme I fixed some formatting and linting issues and then tweaked the subheading language a bit.

Also, the margins and padding didn't seem to fit the design. Check out the css changes I made and if those look good to you, I'm good to merge.

2020-10-13 18:19 UTC, merged